version: "3.9"

services:
  # MongoDB No-SQL Document Database
  mongo:
    image: mongo
    container_name: javabot_mongodb
    restart: always
    ports:
      - "27171:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  # Web-Based Admin Tool for MongoDB. Connect via http://localhost:5050
  mongo-express:
    image: mongo-express
    container_name: javabot_mongo-express
    restart: always
    ports:
      - "5050:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
